# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



# analize = Analyser("XRP-USD", "2021-11-01", "2021-11-24")


"""
to do:
    
    [*] Make design in QT. DONE!
    [ ] embedd functionality.
    [ ] Push to githbu.
    [ ] Make Blog and documentation.


"""


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtWidgets import QApplication, QWidget, QMainWindow
import sys
# from CurrencyAnalizer import Analyser

class Ui_GUI(object):
    

    def Ploter(self):
        print('Hello')

    def setupUi(self, GUI):
        GUI.setObjectName("GUI")
        GUI.setWindowModality(QtCore.Qt.WindowModal)
        GUI.resize(679, 381)
        GUI.setMouseTracking(False)
        GUI.setAcceptDrops(False)
        GUI.setWindowOpacity(1000.0)
        GUI.setStyleSheet("background: black; color:white; border-radius: 3px; font-family: sans-serif;")
        GUI.setTabShape(QtWidgets.QTabWidget.Triangular)
        GUI.setDockNestingEnabled(False)
        GUI.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(GUI)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setStyleSheet("background: black; color: white")
        self.centralwidget.setObjectName("centralwidget")
        self.PlotButton = QtWidgets.QPushButton(self.centralwidget)
        self.PlotButton.clicked.connect(self.Ploter)
        self.PlotButton.setFocus()
        
        self.PlotButton.setGeometry(QtCore.QRect(110, 260, 121, 31))
        self.PlotButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PlotButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.PlotButton.setToolTipDuration(-2)
        self.PlotButton.setAutoFillBackground(False)
        self.PlotButton.setStyleSheet("background: white; color: black; border-radius: 10px; font-family: sans-serif;")
        self.PlotButton.setObjectName("PlotButton")

        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(90, 120, 161, 21))
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background: white; color: black; border-radius: 3px; font-family: sans-serif;text-align:center;")
        self.textEdit.setAcceptRichText(True)
        self.textEdit.setPlaceholderText("Currency Symbol")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(90, 170, 161, 21))
        self.textEdit_2.setStyleSheet("background: white; color: black; border-radius: 3px; font-family: sans-serif;")
        self.textEdit_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_2.setTabChangesFocus(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(90, 220, 161, 21))
        self.textEdit_3.setStyleSheet("background: white; color: black; border-radius: 3px; font-family: sans-serif;")
        self.textEdit_3.setObjectName("textEdit_3")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(350, 50, 311, 281))
        self.textBrowser_2.setStyleSheet("border: 1px solid white; border-radius: 20px;padding:10")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 20, 301, 341))
        self.frame.setStyleSheet("background: rgb(0, 0, 5); border-radius:3px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.PlotButton.raise_()
        self.textEdit.raise_()
        self.textEdit_2.raise_()
        self.textEdit_3.raise_()
        self.textBrowser_2.raise_()
        
        
        GUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(GUI)
        QtCore.QMetaObject.connectSlotsByName(GUI)
    
    def retranslateUi(self, GUI):
        _translate = QtCore.QCoreApplication.translate
        GUI.setWindowTitle(_translate("GUI", "Currency analyzer"))
        self.PlotButton.setText(_translate("GUI", "Plot"))
        self.textEdit_2.setPlaceholderText(_translate("GUI", "Start date"))
        self.textEdit_3.setPlaceholderText(_translate("GUI", "end date"))
        self.textBrowser_2.setHtml(_translate("GUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'sans-serif\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">instructions:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- To graph any currency you have to specify the symbol and the start and end dates so the programl can scrapp the data as csv then graph it using matplotlib.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">note: only the closing date is graphed, still working on the other things.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Formats</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    Start-date and End date:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">               Date: YEAR-MONTH-DAY</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Symbol</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    Examples: SOL-USD/ETH-USD</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":  
    app = QApplication(sys.argv)
    GUI = QMainWindow()
    Ui_GUI().setupUi(GUI)
    GUI.show()
    sys.exit(app.exec_())

